# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration

require 'coveralls'
Coveralls.wear!

require "html5/tdd"

RSpec.configure do |config|
  config.treat_symbols_as_metadata_keys_with_true_values = true
  config.run_all_when_everything_filtered = true
  config.filter_run :focus

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = 'random'
end

class Example1
  INVALID_HTML = "<!DOCTYPE html>
<html lang='en'>
<head>
<title>title</title>
<meta charset='utf-8'>
<meta content='content' name='description'>
</head>
<body>
<img>
</body>
</html>".freeze

VALID_HTML = "<!DOCTYPE html>
<html lang='en'>
<head>
<title>title</title>
<meta charset='utf-8'>
<meta content='content' name='description'>
</head>
<body>
</body>
</html>".freeze
end
